### PR TITLE
ImGui-based File/Path dialogs

### PR DESCRIPTION
**Pull request by mlauss2**
A file dialog based completely on ImGUI:
https://github.com/aiekick/ImGuiFileDialog

to replace the portable-file-dialogs and give these
dialogs the same look as the rest of the TFE Ui.

Again, mainly for Linux since it eliminates the need
for an external DE-dependent tool to show these dialogs,
and the look-and-feel is also now more similar to the
rest of the UI.

tfe_filedlg2

### CODE REVIEW

**Comment by mlauss2** [comment]
#424 applies cleanly on top of this one.

**Comment by luciusDXL** [comment]
Sorry I have been delaying on this PR, I do plan on getting it in before the editor release if it doesn't break anything.

**Comment by mlauss2** [comment]
updated to latest ImGuiFileDialog upstream, dropped the (turns out unnecessary) C++17 requirement.

**Comment by luciusDXL** [comment]
> updated to latest ImGuiFileDialog upstream, dropped the (turns out unnecessary) C++17 requirement.

Nice, thank you for lowering the C++ requirements.

**Pull request closed without merging**
