### PR TITLE
Drop GLEW in favour of built-in GLAD

### LINKED ISSUE #395: [Linux] Native Linux version launch but black screen
All compiled good
But after launch ./theforceengine only black screen

```
freeartist-devuan@home:~/Downloads/TheDarkForces/TheForceEngine-1.09.540/tfe-build$ ./theforceengine
[Main] The Force Engine 
v1.09.530-13-gd029fe2b

[Paths] Program Path: "/home/freeartist-devuan/Downloads/TheDarkForces/TheForceEngine-1.09.540/tfe-build/"
[Paths] Program Data: "/home/freeartist-devuan/.local/share/TheForceEngine/"
[Paths] User Documents: "/home/freeartist-devuan/.local/share/TheForceEngine/"
[Paths] Source Data: "/home/freeartist-devuan/Downloads/TheDarkForces/DarkForces/"
[Startup] TFE_System::init
[Display] Vertical Sync enabled.
[RenderBackend] OpenGL Device Tier: 1
[Startup] TFE_AudioSystem::init
[Audio] SDLAudio using interface 'pulseaudio'
[Audio] Device 00: Built-in Audio Analog Stereo
[Audio] Starting up audio stream for device '<autoselect>'
[Startup] TFE_MidiPlayer::init
[Startup] TFE_Polygon::init
[Startup] TFE_Image::init
[Startup] TFE_FrontEndUI::init
[MemoryRegion] Allocated new memory block in region 'game' - new size is 1 blocks, total size is '8388608'
[MemoryRegion] Allocated new memory block in region 'level' - new size is 1 blocks, total size is '8388608'
[Progam Flow] The Force Engine Game Loop Started
```

Screenshot_2024-03-13_02-57-51

### PR DESCRIPTION
**Pull request by mlauss2**
Drop GLEW in favor of GLAD-generated built-in loader.
- This drops an extra external library dependency (glew)
- On Linux no system OpenGL libraries/headers are required to build TFE any more
- All the platform specific stuff (windowing, library loading, symbol
  resolution) is now fully handled by SDL2, no more wayland workarounds necessary (i.e. #386 )
    
The GLAD loader is GL4.6, while TFE's minimum is still GL3.3;
the Anisotropy stuff, which is core GL4.5, has been wrapped around
availability of EXT_texture_filter_anisotropic (which most GL2
drivers support).

This PR also updates ImGUI to version 1.90.9 because after the current in-tree 1.72 it also dropped GLEW.

This should also fix #395  which was caused by TFE explicitly linking to an OpenGL library, which, after this PR, is no longer necessary.

After applying this PR, the dependencies change to:
```diff
-Shared library: [libOpenGL.so.0]
-Shared library: [libGLX.so.0]
-Shared library: [libGLU.so.1]
-Shared library: [libGLEW.so.2.2]
-Shared library: [libGL.so.1]
-Shared library: [libX11.so.6]
 Shared library: [libSDL2-2.0.so.0]
 Shared library: [libSDL2_image-2.0.so.0]
 Shared library: [librtmidi.so.7]
```
i.e. no explicit dependency on OpenGL and windowing system, just SDL2.

Another nice sideeffect at least on Linux is that "zink" (OpenGL over Vulkan) also works now:
image
Performance on my radeon is about 66% of the direct opengl path.

### CODE REVIEW

**Comment by mlauss2** [comment]
editor needs more imgui fixing

**Comment by mlauss2** [comment]
I fixed up the non-opening modal windows in the editor.

**Comment by mlauss2** [comment]
I've also now tested this successfully on Windows as well.

**Comment by mlauss2** [comment]
I've split the 2 patches into separate PRs (with #421 to start)

**Comment by luciusDXL** [comment]
I don't have any specific attachment to GLEW (other than using it in several projects), so this seems fine. I will patch it in after the next release.

**Pull request closed without merging**
